name: Ejemplo de Flujo de Trabajo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest
    environment: PROD
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@paulgualambo' # Reemplaza <USERNAME> con tu nombre de usuario u organización
          always-auth: true
      - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN }}" > .npmrc          
      - run: npm ci
      - run: npm run build
      - run: npx semantic-release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PACKAGES_PAT }} # Asegúrate de reemplazar GH_PACKAGES_PAT con el nombre de tu secreto
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
