jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@paulgualambo' # Reemplaza <USERNAME> con tu nombre de usuario u organización
          always-auth: true
      - run: npm ci
      - run: npm run build
      - run: npx semantic-release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PACKAGES_PAT }} # Asegúrate de reemplazar GH_PACKAGES_PAT con el nombre de tu secreto
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
